### ISSUE TITLE
Analysis search filter doesn’t filter for Author name

### ISSUE THREAD

**Issue by chienleng** [opennem/openelectricity#25]
Typing an author's name in the search filter doesn't display the articles for that author. 

<img width="377" alt="Screenshot 2024-07-12 at 2 55 45 PM" src="https://github.com/user-attachments/assets/cf5bb75e-7e13-4064-9aa2-eab4050d1c79">

**Comment by Phuc-Hong-Tran** [comment]
Addressed in PR#27
